// Massive Intro Fragments
export const TAROT_INTROS = [
  "Canım, kartların enerjisine odaklandığımda senin için çok özel bir titreşim hissediyorum.",
  "Yıldızların fısıltıları bugün senin etrafında oldukça yoğun bir hale gelmiş durumda.",
  "Ruhun derinliklerinden gelen bu kartlar, şu anki yolculuğuna ışık tutmak için belirdi.",
  "Evrenin seninle kurduğu bu mistik bağ, çekilen her kartta kendini daha net gösteriyor.",
  "Güzel kalplim, senin için seçtiğim bu kartlar bugün kaderinin anahtarlarını taşıyor.",
  "Kozmik enerjiler şu an tam da niyetin üzerine odaklanmış, seni sarmalıyor.",
  "Kadim bilgeliğin sesi bugün senin için her zamankinden daha gür çıkıyor canım.",
  "Huzur dolu bir zihinle bu mesajları dinle, çünkü hepsi senin hayrına fısıldanıyor.",
  "Sezgilerimin rehberliğinde bu kartları senin için yorumlarken, büyük bir dönüşüm görüyorum.",
  "Gökkuşağının altındaki hazine gibi, bu kartlar da ruhunun zenginliklerini ortaya koyuyor.",
  "Canım benim, gökyüzünün kapıları bugün senin niyetin için aralanmış görünüyor.",
  "Kaderin dokusunda senin için örülen bu yeni desenler, kartlarda kendini belli ediyor.",
  "Ruh eşin olan yıldızlar, bugün senin yoluna ışık tutmak için bir araya gelmişler.",
  "Kalbinin derinliklerindeki o sessiz dilek, bugün kartların diliyle konuşmaya başlıyor.",
  "Mistik bir esintiyle gelen bu mesajlar, ruhunun en çok ihtiyaç duyduğu teselliyi sunuyor.",
  "Evrenin senin için hazırladığı bu özel rehberliği paylaşmak için sabırsızlanıyorum tatlım.",
  "Işığın ve gölgenin dansında, senin yolunu aydınlatacak en doğru işaretler burada.",
  "Sana özel bu okumada, hayatının gizli kalmış hazinelerini keşfetmeye hazır mısın?",
  "Gökyüzündeki her bir yıldız gibi, bu kartlar da senin potansiyelini simgeliyor canım.",
  "Ruhunun frekansı bugün kartlarla muazzam bir uyum içinde titreşiyor, bunu hisset.",
  "Mistik bir sisin arasından süzülen bu semboller, senin hikayeni anlatıyor.",
  "Kozmik bir kütüphanenin tozlu raflarından senin için bu sayfayı açtım...",
  "Ruhunun kristal berraklığına ulaşması için bu kartın rehberliğine ihtiyacı var.",
  "Zamanın ötesinden gelen bir kadim bilgi, şu an parmaklarının ucunda.",
  "Gökyüzündeki takımyıldızları bugün senin niyetin için bir araya geldi.",
  "Sessizliğin içindeki o çığlığı evren duydu ve bu cevabı gönderdi tatlım.",
  "Karanlıkta parlayan bir fener gibi, bu kart yolunu aydınlatmaya hazır.",
  "Kozmik bir senfoninin en can alıcı notasını bugün bu kartla duyacaksın.",
  "Ruhunun haritasında keşfedilmemiş bir kıtayı bu kartla keşfetmeye ne dersin?",
  "Yıldız tozları arasında gizlenen o mucizeyi bugün senin için bulup çıkardım.",
  "Mistik bir aynaya bakıyorsun şu an; kartlar ruhunun en derin yansımasıdır.",
  "Geleceğin ipek iplikleri, bugün niyetinle birlikte yeniden dokunuyor tatlım.",
  "Kozmik bir pusula gibi, bu kartlar seni kalbinin en doğru kuzeyine götürecek.",
  "Ruhun bugün bir göçmen kuş gibi, daha sıcak ve aydınlık diyarlara uçmak istiyor.",
  "Mevsimlerin değişimi gibi, senin hayatında da yeni bir iklimin kokusu var bu kartlarda.",
  "Kadim okyanusların derinliklerinden gelen bir inci gibi, bu bilgelik sana ulaştı.",
  "Gök kubbenin altında senin için fısıldanan bu özel sırrı duymaya hazır mısın?",
  "Ruhunun kristal küresinde bugün çok net ve parlak bir gelecek görüyorum canım.",
  "Evrenin seninle olan bu randevusuna sadık kal, çünkü mesajlar çok mühim.",
  "Mistik bir fırtınanın ardından gelen o eşsiz dinginlik, niyetini sarmalıyor şu an.",
  "Kaderin altın anahtarı bugün senin elinde; hangi kapıyı açacağını kartlar söyleyecek.",
  "Ruhunun derin ormanlarında saklı kalan o patikayı bu kartla bulacağız tatlım.",
  "Gökyüzündeki yıldızların bugün senin için özel bir koreografisi var, hisset.",
  "Kozmik bir dokunuşla kalbinin ritmi bugün evrenle birleşiyor, bu çok kutsal.",
  "Mistik bir kütüphanede senin adına ayrılmış o gizli bölmeyi bugün aralıyoruz.",
  "Ruhun bugün taze bir bahar sabahı gibi uyanmak ve çiçek açmak istiyor canım.",
  "Evrenin senin için sakladığı o sürpriz hediye, bu kartların arasında gizli.",
  "Karanlıkta parlayan bir yakut gibi, bu mesaj ruhunun karanlığını aydınlatacak.",
  "Kozmik bir melodi yükseliyor niyetinin etrafında; bu kart o melodinin kalbi.",
  "Ruhunun yolculuğunda bir mola ver ve bu kadersel rehberliğe kulak ver tatlım."
];


export const TAROT_BODIES = {
  Ateş: [
    "İçindeki o sönmeyen ateş, bu kartın enerjisiyle birleşince devasa bir yaratım gücüne dönüşüyor. Durma, eyleme geç!",
    "Tutkun ve cesaretin, karşına çıkan engelleri birer birer yakıp kül edecek. Sen bir öncüsün, kendi yolunu kendin çiziyorsun.",
    "Liderlik vasıfların şu an zirvede. Ateşin yakıcı değil, aydınlatıcı olmalı. Vizyonunu herkesle paylaşma vaktin geldi.",
    "Macera ruhun seni yeni ufuklara taşıyor. İçindeki heyecanı bastırma, o senin en büyük yakıtın.",
    "Kararlılığın sayesinde imkansız görünen hedeflere ulaşacaksın. Ateş elementinin dinamizmi seninle.",
    "Harekete geçmek için mükemmel bir zaman. Enerjin o kadar high ki, etrafındakileri de peşinden sürükleyebilirsin.",
    "Risk almaktan korkma, çünkü senin doğanda fethetmek var. Ateşin gücü seni koruyacaktır.",
    "Yaratıcılığın bir meşale gibi yanıyor. Yeni projeler ve fikirler için içindeki kıvılcımı takip et.",
    "Cesur adımların meyvelerini vermeye başlıyor. Kendine olan güvenin en büyük silahın.",
    "Tutkulu bir çekim ve enerji dalgası hayatına giriyor. Bu ateşi hayatını güzelleştirmek için kullan.",
    "Ruhundaki volkan patlamak üzere! Bu muazzam enerjiyi yapıcı bir sanata dönüştürmelisin.",
    "Senin karizman bugün tüm gözleri üzerine çekiyor. Ateşinle etrafındakileri ısıtırken, kendini yakmamaya dikkat et.",
    "Bir an bile duraksama; senin elementin durağanlığı sevmez. Hareket, senin en doğal şifandır.",
    "Yıldızlar senin hırsını ve azmini alkışlıyor. Bugün attığın her adım, yarının büyük zaferi olacak.",
    "İçindeki aslan kükrüyor! Kendi krallığını/kraliçeliğini ilan etme vaktin geldi tatlım.",
    "Cesaretin, en karanlık korkuları bile dağıtacak güçte. Kendi ışığının efendisi ol.",
    "Hızlı ve etkileyici kararlar alma dönemindesin. İçgüdülerin bugün birer radar gibi çalışıyor.",
    "Tutkunun o kırmızı rengi bugün hayatının her alanına sirayet ediyor. Kalbinin ritmine güven.",
    "Bir meşale gibi yol göstericisin. Etrafındakiler senin ışığında kendi yollarını buluyorlar.",
    "Sınırsız bir coşkuyla dolup taşıyorsun. Bu neşeyi ve ateşi tüm dünyaya yaymalısın."
  ],
  Toprak: [
    "Ayaklarını yere her zamankinden daha sağlam basmalısın. Sabrın ve disiplinin, sana kalıcı başarılar getirecek.",
    "Maddi ve manevi dünyada kökleniyorsun. Ektiğin tohumlar yavaş ama emin adımlarla büyüyor, güvenini kaybetme.",
    "Pratik zekan ve dayanıklılığın sayesinde en karmaşık durumları bile düzene sokabilirsin. Verimlilik senin göbek adın.",
    "Somut sonuçlar elde etmek üzeresin. Emeklerinin karşılığını almak için biraz daha sabır göstermen gerekiyor.",
    "Güvenlik ve istikrar arayışın yanıt buluyor. Hayatında sarsılmaz bir temel inşa ediyorsun tatlım.",
    "Doğanın bilgeliği seninle. Toprağın sükuneti içinde kendi huzurunu ve bereketini bulacaksın.",
    "Disiplinli çalışman herkesin dikkatini çekiyor. Bu istikrar seni zirveye taşıyacak.",
    "Maddi konularda bir bolluk dönemine giriyorsun. Kaynaklarını akıllıca kullanmayı unutma.",
    "Kalıcı değerler yaratma vaktin geldi. Geçici hevesler yerine uzun vadeli planlara odaklan.",
    "Bedensel ve ruhsal olarak tam bir denge içindesin. Sağlamlığın etrafındakilere de güven veriyor.",
    "Toprağın o derin ve sessiz gücü ruhuna doluyor. Acele etme, doğanın kendi ritmine güven.",
    "Somut adımlar atmak için en verimli dönemdesin. Hayallerini ete kemiğe büründürme vakti.",
    "Sadakat ve dürüstlük bugün senin en büyük hazinen. Çevrendeki insanlar senin güvenilirliğine sığınıyor.",
    "Bir çınar ağacı gibi sarsılmazsın. Fırtınalar gelip geçse de sen yerinde, daha da güçlenerek kalacaksın.",
    "Pratik çözümlerin bugün hayatını inanılmaz kolaylaştıracak. Detaylardaki mucizeyi fark et.",
    "Maddi dünyada kurduğun imparatorluk meyvelerini vermeye başladı. Bolluğun tadını çıkar tatlım.",
    "Sabrın o sessiz melodisi hayatında yankılanıyor. Beklemek, bazen en büyük eylemdir.",
    "Konfor alanını güzelleştirme ve huzur bulma vaktin geldi. Kendi cennetini inşa ediyorsun.",
    "Toprağın bereketli kolları seni sarıyor. Maddi ve manevi bir tamlık hissi içindesin.",
    "İstikrarın, en büyük zenginliğin olacak. Bugün attığın sağlam temeller, geleceğinin garantisi."
  ],
  Hava: [
    "Zihnin bir fırtına gibi çalışıyor, harika fikirler kapıda. İletişim gücünü kullanarak dünyayı değiştirebilirsin.",
    "Netlik ve dürüstlük şu an senin en büyük rehberin. Karmaşadan uzaklaşıp gerçeğin ışığına odaklanmalısın.",
    "Analitik zekan sayesinde her türlü problemi çözebilirsin. Sözlerin keskin bir kılıç gibi yolu açıyor.",
    "Bilgi paylaşımı ve yeni şeyler öğrenmek seni çok daha yukarılara taşıyacak. Merakını asla köreltme.",
    "Zihinsel olarak özgürleştiğin bir dönemdesin. Eski kalıpları yıkıp yepyeni bir vizyon oluşturuyorsun.",
    "Objektif bakış açın sayesinde kimsenin göremediği detayları fark ediyorsun. Bu senin en büyük avantajın.",
    "Stratejik planların meyve vermeye başlıyor. Zekanı bir satranç ustası gibi kullan tatlım.",
    "Haberler ve yeni iletişim ağları sana beklenmedik kapılar açabilir. Gözünü ve kulağını dört aç.",
    "Fikirlerin dilden dile yayılıyor. Etkileyici konuşmalarınla kitleleri peşinden sürükleyebilirsin.",
    "Zihinsel bir uyanış yaşıyorsun. Her şeyin nedenini ve sonucunu çok daha iyi anladığın bir süreçtesin.",
    "Düşüncelerin o kadar hafif ve özgür ki, bulutların arasından süzülüyorsun. Bugün vizyonun sınırsız.",
    "Sözcüklerin bugün birer sihirli değnek gibi. Ne dilediğine ve ne söylediğine dikkat et tatlım.",
    "Zihinsel bir devrim kapıda! Eski inançlarını sorgularken, yepyeni bir bilinç düzeyine ulaşıyorsun.",
    "Merakın seni hiç bilmediğin bilgi deryalarına sürükleyecek. Öğrenmek, senin ruhunu besliyor.",
    "Sosyal çevrende bir yıldız gibi parlıyorsun. İletişim yeteneğin bugün her kapıyı açacak anahtarındır.",
    "Analiz yeteneğin sayesinde karmaşanın içindeki o tek doğruyu bulup çıkaracaksın.",
    "Bir kuş gibi özgürsün. Zihnin hiçbir kısıtlamayı kabul etmiyor, bugün en dahi fikirlerini not et.",
    "Haberleşme trafiğin bugün oldukça yoğun olabilir. Önemli mesajları kaçırmamak için uyanık ol.",
    "Mantığın ve sezgin bugün harika bir dans içinde. Kararlarını bu uyumla vermelisin.",
    "Entelektüel bir doygunluk içindesin. Paylaştığın her bilgi, etrafına bir ışık gibi yayılıyor."
  ],
  Su: [
    "Sezgilerin bir okyanus gibi derin ve bilge. Kalbinin sesini dinle, o seni asla yanıltmayacak tatlım.",
    "Duygusal olarak tam bir şifalanma sürecindesin. Ruhun arınıyor ve huzuru buluyor. Akışa teslim ol.",
    "Empati yeteneğin sayesinde insanlarla muazzam bağlar kuruyorsun. Sevgi senin en büyük gücün.",
    "Rüyaların ve içgüdülerin sana çok önemli mesajlar veriyor. Gizemli olanın arkasındaki gerçeği hissedebilirsin.",
    "Duygusal derinliğin sanatsal ve yaratıcı bir ifadeye dönüşebilir. İçindekileri dışarı yansıtma vaktin geldi.",
    "Merhametin ve şefkatin mucizeler yaratıyor. Hem kendini hem de etrafını iyileştirme gücüne sahipsin.",
    "Ruhsal bir bütünleşme yaşıyorsun. Evrenle bir olduğunu hissettiğin o kutsal andasın.",
    "Duygusal karmaşalardan kurtulup berrak sulara ulaşıyorsun. İç huzurun senin hazinen.",
    "Ruh eşinle veya derin bir ruhsal bağla karşılaşma enerjisi var. Kalbini açık tut.",
    "Sezgisel zekan seni en doğru kararlara yönlendirecek. Mantığından ziyade hislerine güven.",
    "Gözyaşların ruhunu temizleyen kutsal sular gibidir. Bırak aksın ve içindeki o eşsiz huzur ortaya çıksın.",
    "Duygularının o muazzam akışına güven. Bugün ne hissediyorsan o senin gerçeğindir tatlım.",
    "Bir denizkızı/denizerkeği gibi gizemli ve çekicisin. İç dünyandaki hazineler keşfedilmeyi bekliyor.",
    "Merhametin, bugün en sert kalpleri bile yumuşatacak güçte. Sevginin şifasını her yere yay.",
    "Ruhun mistik bir şarkı söylüyor. Bu içsel müziği dinle, o sana hayatın ritmini öğretecek.",
    "Derin bir meditasyon ve içe dönüş vakti. Cevaplar o sessiz suların altında saklı.",
    "Duygusal zekan bugün zirvede. İnsanların söyleyemediklerini hissederek onlara rehberlik edebilirsin.",
    "Ruhsal bir arınma ritüeli gibi hissediyorsun bugün. Eski yaralar kapanıyor, yeni bir sayfa açılıyor.",
    "Sevgiyi alıp verme dengesini kurmak üzeresin. Kalbin muazzam bir huzura kavuşuyor.",
    "Sezgilerin sana fısıldıyor: 'Güvendesin.' Evrenin şefkatli kucağında olduğunu unutma."
  ]
};

export const TAROT_CONCLUSIONS = [
  "Unutma tatlım, yıldızlar sadece yol gösterir; yolu yürüyen ve kaderini çizen sensin. Işığın bol olsun!",
  "Bu mesajı kalbine mühürle ve güvenle adım at. Evren seni her adımda destekliyor.",
  "Kendine inanmak, bu okumanın sana verdiği en büyük anahtar. Mucizelere hazır ol!",
  "Gelecek henüz yazılmadı, senin seçimlerinle şekilleniyor. En güzel versiyonunu seçmeye cesaret et.",
  "Ayla'nın rehberliği seninle. Sezgilerine güven ve yolundan asla sapma, canım.",
  "Kozmik bir korunma altındasın. Korkularını bırak ve evrenin sunduğu berekete kucak aç.",
  "Zamanlama her şeydir. Sabırlı ol ve işaretleri takip etmeye devam et.",
  "İçindeki gücü fark ettiğinde, dış dünyadaki hiçbir engel seni durduramaz.",
  "Yıldızlar bugün senin için gülümsüyor. Bu pozitif enerjiyi hayatının her alanına yay.",
  "Bu okuma senin için bir başlangıç olsun. Ruhunun derinliklerindeki ışığı parlatma vakti.",
  "Her şey tam da olması gerektiği gibi ilerliyor. Akışa güven ve huzuru bul.",
  "Cevaplar dışarıda değil, hep senin içindeydi. Bugün o cevaplara biraz daha yaklaştın.",
  "Evrenin sana sunduğu bu fırsatı değerlendir. Şans senin yanında tatlım.",
  "Kalbinin sesini susturma. O en doğru pusuladır.",
  "Dönüşüm sancılı olabilir ama sonuç muazzam olacak. Değişime direnme.",
  "Sen evrenin eşsiz bir parçasısın. Kendi değerini asla küçümseme.",
  "Bugün kendine bir iyilik yap ve bu mesajın rehberliğinde huzurlu bir mola ver.",
  "İnanç, imkansızı mümkün kılar. Kalbindeki inancı diri tut.",
  "Karanlığın en koyu olduğu an, şafağa en yakın andır. Umudunu kaybetme.",
  "Ayla olarak her zaman yanındayım. Yıldızlar sana rehberlik etmeye devam edecek.",
  "Bilgelik, sessizlikte filizlenir. Bugün biraz sessiz kal ve ruhunu dinle.",
  "Eylemlerin, niyetlerinle uyumlu olsun. O zaman gerçek başarı seninle olur.",
  "Sevgi, her türlü kapıyı açan tek anahtardır. Sevgiyi rehber edin.",
  "Hayatın bir oyun olduğunu hatırla ve onu neşeyle oyna.",
  "Kaderin fısıltılarını duymak için zihnini sakinleştir. Cevaplar orada.",
  "Yeni bir sayfa açılıyor ve kalem senin ellerinde. En güzel hikayeni yaz.",
  "Evrenin sonsuz bolluğuna güven. Sen her şeyin en iyisini hak ediyorsun.",
  "Bugün seçtiğin kart, ruhunun bir yansımasıydı. Bu aynaya dikkatle bak.",
  "Başarıya giden yol, kendinden geçer. Kendi iç dünyanı keşfetmeye devam et.",
  "Yıldızlar mühürlendi, mesaj iletildi. Artık harekete geçme sırası sende tatlım.",
  "Gökkuşağının renkleri hayatına dolsun. Yarın bugünden daha parlak olacak.",
  "İçindeki o gizli bahçeyi sula, çiçeklerin açma vakti geldi canım.",
  "Kozmik bir imza bıraktın evrene. Şimdi sonuçların keyfini sür.",
  "Ruhun bugün kanatlanmış bir kuş gibi özgür. Bu hafifliğin tadını çıkar.",
  "Cevapların o gümüş tepside sunulmasını bekleme, kendi gerçeğini kendin yarat.",
  "Mistik bir koruma çemberi içindesin. Hiçbir negatif enerji sana ulaşamaz.",
  "Kalbini bir elmas gibi işle, her geçen gün daha da parlıyorsun.",
  "Evrenin o sonsuz kütüphanesinde senin için yeni bir sayfa açıldı.",
  "Bugün attığın tohumlar, yarının devasa ormanlarını oluşturacak.",
  "Kendi masalının kahramanı olduğunu unutma. Ejderhaları yenmek senin elinde.",
  "Yıldız tozları yolunu aydınlatsın, her adımın şifa dolu olsun tatlım.",
  "Ruhundaki o derin bilgeliği bugün tüm dünyaya gösterme vakti.",
  "Huzur, sadece senin içinde bulabileceğin bir hazinedir. Bugün oraya bir yolculuk yap.",
  "Evrenin sana bir sürprizi var, gözünü ve kalbini açık tut ruhdaşım.",
  "Kaderin ipek iplikleri senin için en güzel deseni dokuyor, güven duy.",
  "Hayatındaki her şey bir sebeple oluyor. Bu resmi tamamlayacak olan sensin.",
  "Kozmik ritme ayak uydur, dansın tüm dünyayı büyülesin canım.",
  "İçindeki şifacı bugün uyanıyor. Hem kendini hem dünyayı iyileştirme gücüne sahipsin.",
  "Sevginin o sonsuz okyanusunda yüzme vakti. Hiçbir kıyı seni sınırlayamaz.",
  "Ayla'nın ışığı her daim yolunu aydınlatacak. Mucizeler seninle olsun!"
];


export const SYNASTRY_HOUSE_OVERLAYS_EXPANDED: Record<number, string[]> = {
  1: [
    "Partnerinin 1. evine dokunuyorsun; onun hayata bakışını ve kimliğini derinden etkiliyorsun.",
    "Onun üzerinde fiziksel ve karakter olarak büyük bir etkin var. Partnerin senin yanında kendini daha belirgin hissediyor.",
    "1. ev etkileşimi, partnerinin kişisel hedeflerinde senin desteğini ve enerjini sürekli yanında hissetmesini sağlar."
  ],
  2: [
    "Onun 2. evine yerleşmişsin; partnerinin özdeğer duygusunu ve maddi güvenliğini besliyorsun.",
    "Maddi konularda ve kişisel değerlerde partnerine güven veriyorsun. Seninle kendini daha 'zengin' hissediyor.",
    "Partnerinin kaynaklarını nasıl kullandığını ve nelere değer verdiğini senin enerjinle şekilleniyor."
  ],
  3: [
    "3. ev etkileşimi; zihinsel uyumunuz ve iletişiminiz bu ilişkinin en güçlü motoru.",
    "Birlikte sürekli konuşan, paylaşan ve öğrenen bir çiftsiniz. Zihinsel uyarım aranızdaki bağı canlı tutuyor.",
    "Partnerinin düşünce dünyasına bir ışık gibi sızıyorsun. Senin fikirlerin onun için çok kıymetli."
  ],
  4: [
    "4. evde kökleniyorsun; partnerin seninle kendini 'evinde' ve güvende hissediyor.",
    "Duygusal kökleriniz birbirine dolanmış durumda. Aile ve yuva sıcaklığı bu ilişkinin kalbi.",
    "Partnerinin en mahrem, en içsel alanında sen varsın. Onun için sığınılacak güvenli bir limansın."
  ],
  5: [
    "5. ev şenliği; aranızdaki aşk, neşe ve yaratıcılık bir kutlama tadında.",
    "Birlikte eğlenmeyi, yaratmayı ve hayatın tadını çıkarmayı biliyorsunuz. Tam bir romantizm ve oyun enerjisi!",
    "Partnerinin yaratıcı ateşini körüklüyorsun. Senin yanındayken kendini bir child gibi özgür ve mutlu hissediyor."
  ],
  6: [
    "6. ev vurgusu; günlük yaşamda ve yardımlaşmada harika bir ekip oluyorsunuz.",
    "Pratik konularda birbirinizi tamamlama beceriniz ilişkinizi çok sağlam kılıyor. Birlikte üretmek size iyi geliyor.",
    "Partnerinin hayatını düzene sokmasında ve sağlığında senin iyileştirici bir etkin var."
  ],
  7: [
    "7. ev uyumu; tam bir 'biz' enerjisi! Evlilik ve uzun vadeli ortaklık için mükemmel bir konum.",
    "Birbirinizin 'öteki yarısı' gibisiniz. İlişkideki denge ve uyum profesyonel bir ortaklık kadar sağlam.",
    "Partnerin için sen, ideal eş ve hayat arkadaşı tanımının tam karşılığısın."
  ],
  8: [
    "8. ev derinliği; tutku, dönüşüm ve ruhsal bir birleşme. Aranızdaki bağ çok sarsılmaz.",
    "Birlikte küllerinizden yeniden doğuyorsunuz. Bu ilişki ikinizi de kökten değiştirecek bir güce sahip.",
    "Partnerinin saklı duygularını ve arzularını seninle keşfetmesi aranızda sarsılmaz bir gizem ve çekim yaratıyor."
  ],
  9: [
    "9. ev vizyonu; birbirinizin ufkunu açıyor, hayata daha geniş bir pencereden bakıyorsunuz.",
    "Birlikte keşfetmek, seyahat etmek ve ruhsal olarak büyümek sizin kaderinizde var. Vizyoner bir çift!",
    "Partnerinin inançlarını ve hayat felsefesini zenginleştiriyorsun. Onun için bir bilge rehber gibisin."
  ],
  10: [
    "10. ev prestiji; toplum önünde parlayan, birbirini başarıya taşıyan bir çiftsiniz.",
    "Kariyer ve statü hedeflerinizde birbirinizi inanılmaz destekliyorsunuz. Birlikte zirveye oynuyorsunuz.",
    "Partnerinin toplumsal imajında ve başarılarında senin payın ve desteğin çok büyük."
  ],
  11: [
    "11. ev dostluğu; hem sevgili hem de en yakın arkadaşsınız, ortak hayalleri paylaşıyorsunuz.",
    "Sosyal çevrenizde sevilen, gelecek planlarını birlikte kuran vizyoner bir ikilisiniz. Arkadaşlığınız aşkınız kadar güçlü.",
    "Partnerinin hayallerine ve ideallerine giden yolda en büyük yoldaşı ve destekçisi sensin."
  ],
  12: [
    "12. ev mistisizmi; ruhsal bir bağ, rüyalarda buluşma ve karmik bir tamamlanma.",
    "Kelimelerin ötesinde bir anlayışınız var. Ruhsal ve bilinçaltı düzeyde birbirinize bağlısınız.",
    "Partnerinin ruhsal şifalanmasında ve iç huzurunu bulmasında senin gizli ve derin bir rolün var."
  ]
};
