export const LOCAL_TAROT_CARDS = [
  {
    "name": "The Fool",
    "name_short": "ar00",
    "value": "0",
    "value_int": 0,
    "type": "major",
    "meaning_up": "New beginnings, optimism, trust in life.",
    "meaning_rev": "Recklessness, risk-taking, inconsiderateness.",
    "desc": "A young man stands on the edge of a cliff, looking out into the unknown."
  },
  {
    "name": "The Magician",
    "name_short": "ar01",
    "value": "1",
    "value_int": 1,
    "type": "major",
    "meaning_up": "Action, the power to manifest, creativity.",
    "meaning_rev": "Manipulation, poor planning, latent talents.",
    "desc": "A figure with one hand pointed to the sky and the other to the earth."
  },
  {
    "name": "The High Priestess",
    "name_short": "ar02",
    "value": "2",
    "value_int": 2,
    "type": "major",
    "meaning_up": "Inaction, intuition, mystery.",
    "meaning_rev": "Unveiling secrets, hidden enemies, lack of spiritual clarity.",
    "desc": "A woman seated between two pillars, B and J."
  },
  {
    "name": "The Empress",
    "name_short": "ar03",
    "value": "3",
    "value_int": 3,
    "type": "major",
    "meaning_up": "Abundance, nurturing, fertility, luxury.",
    "meaning_rev": "Creative block, dependency, emptiness.",
    "desc": "A motherly figure seated on a throne in a lush garden."
  },
  {
    "name": "The Emperor",
    "name_short": "ar04",
    "value": "4",
    "value_int": 4,
    "type": "major",
    "meaning_up": "Structure, authority, control, fatherhood.",
    "meaning_rev": "Tyranny, rigidity, coldness, chaos.",
    "desc": "A stern figure seated on a stone throne decorated with rams' heads."
  },
  {
    "name": "The Hierophant",
    "name_short": "ar05",
    "value": "5",
    "value_int": 5,
    "type": "major",
    "meaning_up": "Tradition, conformity, morality, ethics.",
    "meaning_rev": "Rebellion, subversiveness, new horizons.",
    "desc": "A religious figure seated between two pillars, blessing two followers."
  },
  {
    "name": "The Lovers",
    "name_short": "ar06",
    "value": "6",
    "value_int": 6,
    "type": "major",
    "meaning_up": "Partnerships, duality, union, choice.",
    "meaning_rev": "Disharmony, imbalance, misalignment of values.",
    "desc": "A man and woman standing beneath an angel, a choice to be made."
  },
  {
    "name": "The Chariot",
    "name_short": "ar07",
    "value": "7",
    "value_int": 7,
    "type": "major",
    "meaning_up": "Direction, control, willpower, victory.",
    "meaning_rev": "Lack of control, aggression, self-doubt.",
    "desc": "A warrior driving a chariot pulled by two sphinxes."
  },
  {
    "name": "Strength",
    "name_short": "ar08",
    "value": "8",
    "value_int": 8,
    "type": "major",
    "meaning_up": "Inner strength, bravery, compassion, focus.",
    "meaning_rev": "Self-doubt, weakness, raw emotion.",
    "desc": "A woman calmly closing the jaws of a lion."
  },
  {
    "name": "The Hermit",
    "name_short": "ar09",
    "value": "9",
    "value_int": 9,
    "type": "major",
    "meaning_up": "Contemplation, search for truth, inner guidance.",
    "meaning_rev": "Isolation, loneliness, withdrawal.",
    "desc": "An old man holding a lantern, standing on a mountain peak."
  },
  {
    "name": "Wheel of Fortune",
    "name_short": "ar10",
    "value": "10",
    "value_int": 10,
    "type": "major",
    "meaning_up": "Change, cycles, inevitable fate.",
    "meaning_rev": "Bad luck, resistance to change, breaking cycles.",
    "desc": "A large wheel decorated with various symbols and creatures."
  },
  {
    "name": "Justice",
    "name_short": "ar11",
    "value": "11",
    "value_int": 11,
    "type": "major",
    "meaning_up": "Cause and effect, clarity, truth.",
    "meaning_rev": "Dishonesty, unaccountability, unfairness.",
    "desc": "A figure seated with a sword in one hand and scales in the other."
  },
  {
    "name": "The Hanged Man",
    "name_short": "ar12",
    "value": "12",
    "value_int": 12,
    "type": "major",
    "meaning_up": "Sacrifice, release, martyrdom.",
    "meaning_rev": "Stalling, egoism, resistance.",
    "desc": "A man hanging upside down from a T-shaped tree."
  },
  {
    "name": "Death",
    "name_short": "ar13",
    "value": "13",
    "value_int": 13,
    "type": "major",
    "meaning_up": "End of cycle, beginnings, change, metamorphosis.",
    "meaning_rev": "Fear of change, stagnation, decay.",
    "desc": "A skeleton in armor riding a white horse."
  },
  {
    "name": "Temperance",
    "name_short": "ar14",
    "value": "14",
    "value_int": 14,
    "type": "major",
    "meaning_up": "Middle path, patience, finding meaning.",
    "meaning_rev": "Imbalance, excess, lack of long-term vision.",
    "desc": "An angel pouring liquid between two golden cups."
  },
  {
    "name": "The Devil",
    "name_short": "ar15",
    "value": "15",
    "value_int": 15,
    "type": "major",
    "meaning_up": "Addiction, enslavement, fears, passions.",
    "meaning_rev": "Detachment, breaking free, power reclaimed.",
    "desc": "A winged goat-headed figure with two humans chained to its throne."
  },
  {
    "name": "The Tower",
    "name_short": "ar16",
    "value": "16",
    "value_int": 16,
    "type": "major",
    "meaning_up": "Sudden upheaval, broken pride, disaster.",
    "meaning_rev": "Disaster avoided, delayed upheaval, fear of change.",
    "desc": "A tall tower struck by lightning, people falling from it."
  },
  {
    "name": "The Star",
    "name_short": "ar17",
    "value": "17",
    "value_int": 17,
    "type": "major",
    "meaning_up": "Hope, serenity, the light within.",
    "meaning_rev": "Uninspired, discouraged, faithlessness.",
    "desc": "A woman pouring water into a pond and onto the earth beneath the stars."
  },
  {
    "name": "The Moon",
    "name_short": "ar18",
    "value": "18",
    "value_int": 18,
    "type": "major",
    "meaning_up": "Unseen land, subconscious, illusions.",
    "meaning_rev": "Release of fear, unveiling of truth, confusion.",
    "desc": "A moon in the sky above a path between two towers."
  },
  {
    "name": "The Sun",
    "name_short": "ar19",
    "value": "19",
    "value_int": 19,
    "type": "major",
    "meaning_up": "Happiness, success, health, love.",
    "meaning_rev": "Temporary depression, lack of success, ego.",
    "desc": "A child riding a white horse under a large, smiling sun."
  },
  {
    "name": "Judgement",
    "name_short": "ar20",
    "value": "20",
    "value_int": 20,
    "type": "major",
    "meaning_up": "Rebirth, inner-call, forgiveness.",
    "meaning_rev": "Self-doubt, refusal of self-examination, stagnation.",
    "desc": "An angel blowing a trumpet, people rising from graves."
  },
  {
    "name": "The World",
    "name_short": "ar21",
    "value": "21",
    "value_int": 21,
    "type": "major",
    "meaning_up": "Completion, integration, travel, accomplishment.",
    "meaning_rev": "Lack of completion, lack of closure, delays.",
    "desc": "A figure dancing within a wreath, surrounded by four figures."
  },
  // Wands
  { "name": "Ace of Wands", "name_short": "waac", "value": "ace", "value_int": 1, "type": "wands", "meaning_up": "Creation, invention, enterprise, power.", "meaning_rev": "Fall, decadence, ruin, cloudiness.", "desc": "A hand emerging from a cloud holding a sprouting wand." },
  { "name": "Two of Wands", "name_short": "wa02", "value": "2", "value_int": 2, "type": "wands", "meaning_up": "Planning, making decisions, discovery.", "meaning_rev": "Fear of the unknown, lack of planning.", "desc": "A man looking out over a landscape holding a globe." },
  { "name": "Three of Wands", "name_short": "wa03", "value": "3", "value_int": 3, "type": "wands", "meaning_up": "Expansion, foresight, looking ahead.", "meaning_rev": "Lack of progress, delays.", "desc": "A man looking out at ships from a cliff." },
  { "name": "Four of Wands", "name_short": "wa04", "value": "4", "value_int": 4, "type": "wands", "meaning_up": "Celebration, harmony, homecoming.", "meaning_rev": "Lack of communication, transition.", "desc": "Two people celebrating beneath a floral canopy." },
  { "name": "Five of Wands", "name_short": "wa05", "value": "5", "value_int": 5, "type": "wands", "meaning_up": "Competition, conflict, struggle.", "meaning_rev": "Avoidance of conflict, agreement.", "desc": "Five men fighting with wands." },
  { "name": "Six of Wands", "name_short": "wa06", "value": "6", "value_int": 6, "type": "wands", "meaning_up": "Victory, success, public recognition.", "meaning_rev": "Excessive pride, lack of recognition.", "desc": "A man on a horse with a laurel wreath on his wand." },
  { "name": "Seven of Wands", "name_short": "wa07", "value": "7", "value_int": 7, "type": "wands", "meaning_up": "Defense, perseverance, protection.", "meaning_rev": "Giving up, overwhelmed.", "desc": "A man defending himself from a higher position." },
  { "name": "Eight of Wands", "name_short": "wa08", "value": "8", "value_int": 8, "type": "wands", "meaning_up": "Quick action, movement, speed.", "meaning_rev": "Panic, delays, slowing down.", "desc": "Eight wands flying through the air." },
  { "name": "Nine of Wands", "name_short": "wa09", "value": "9", "value_int": 9, "type": "wands", "meaning_up": "Resilience, grit, last stand.", "meaning_rev": "Burnout, giving up, paranoia.", "desc": "A bandaged man leaning on a wand, standing before eight others." },
  { "name": "Ten of Wands", "name_short": "wa10", "value": "10", "value_int": 10, "type": "wands", "meaning_up": "Burden, responsibility, hard work.", "meaning_rev": "Burnout, delegation, release.", "desc": "A man carrying ten wands towards a town." },
  { "name": "Page of Wands", "name_short": "wapa", "value": "page", "value_int": 11, "type": "wands", "meaning_up": "Inspiration, ideas, discovery.", "meaning_rev": "Setbacks to new ideas, lack of direction.", "desc": "A young person standing with a wand." },
  { "name": "Knight of Wands", "name_short": "wakn", "value": "knight", "value_int": 12, "type": "wands", "meaning_up": "Energy, passion, lust, action.", "meaning_rev": "Anger, impulsiveness, impatience.", "desc": "A knight in armor riding a horse." },
  { "name": "Queen of Wands", "name_short": "waqu", "value": "queen", "value_int": 13, "type": "wands", "meaning_up": "Confidence, social butterfly, focus.", "meaning_rev": "Selfishness, jealousy, pushiness.", "desc": "A queen seated on a throne decorated with lions." },
  { "name": "King of Wands", "name_short": "waki", "value": "king", "value_int": 14, "type": "wands", "meaning_up": "Visionary, leader, entrepreneur.", "meaning_rev": "Impulsiveness, ruthlessness, high expectations.", "desc": "A king seated on a throne decorated with salamanders." },
  // Cups
  { "name": "Ace of Cups", "name_short": "cuac", "value": "ace", "value_int": 1, "type": "cups", "meaning_up": "New feelings, spirituality, intuition.", "meaning_rev": "Emotional loss, blocked creativity.", "desc": "A hand holding a cup overflowing with five streams of water." },
  { "name": "Two of Cups", "name_short": "cu02", "value": "2", "value_int": 2, "type": "cups", "meaning_up": "Partnership, attraction, connection.", "meaning_rev": "Disharmony, break-ups, imbalance.", "desc": "A man and a woman exchanging cups." },
  { "name": "Three of Cups", "name_short": "cu03", "value": "3", "value_int": 3, "type": "cups", "meaning_up": "Friendship, community, celebration.", "meaning_rev": "Overindulgence, gossip, isolation.", "desc": "Three women dancing with cups." },
  { "name": "Four of Cups", "name_short": "cu04", "value": "4", "value_int": 4, "type": "cups", "meaning_up": "Apathy, contemplation, disconnection.", "meaning_rev": "New interest, focus on positive.", "desc": "A man seated under a tree, contemplating three cups." },
  { "name": "Five of Cups", "name_short": "cu05", "value": "5", "value_int": 5, "type": "cups", "meaning_up": "Loss, regret, disappointment.", "meaning_rev": "Acceptance, moving on, finding peace.", "desc": "A cloaked figure mourning three spilled cups." },
  { "name": "Six of Cups", "name_short": "cu06", "value": "6", "value_int": 6, "type": "cups", "meaning_up": "Nostalgia, childhood, reunion.", "meaning_rev": "Living in the past, forgiveness.", "desc": "Two children sharing a cup filled with flowers." },
  { "name": "Seven of Cups", "name_short": "cu07", "value": "7", "value_int": 7, "type": "cups", "meaning_up": "Choices, imagination, illusions.", "meaning_rev": "Clarity, decision-making.", "desc": "A figure contemplating seven cups filled with strange items." },
  { "name": "Eight of Cups", "name_short": "cu08", "value": "8", "value_int": 8, "type": "cups", "meaning_up": "Walking away, disillusionment, leaving.", "meaning_rev": "Fear of moving on, indecision.", "desc": "A figure walking away from eight stacked cups." },
  { "name": "Nine of Cups", "name_short": "cu09", "value": "9", "value_int": 9, "type": "cups", "meaning_up": "Wishes fulfilled, satisfaction, pleasure.", "meaning_rev": "Greed, materialistic, dissatisfaction.", "desc": "A man seated before nine cups." },
  { "name": "Ten of Cups", "name_short": "cu10", "value": "10", "value_int": 10, "type": "cups", "meaning_up": "Harmony, marriage, happiness.", "meaning_rev": "Misalignment of values, family conflict.", "desc": "A family celebrating under a rainbow of ten cups." },
  { "name": "Page of Cups", "name_short": "cupa", "value": "page", "value_int": 11, "type": "cups", "meaning_up": "Creative opportunity, intuitive message.", "meaning_rev": "Emotional immaturity, insecurity.", "desc": "A young person standing with a cup containing a fish." },
  { "name": "Knight of Cups", "name_short": "cukn", "value": "knight", "value_int": 12, "type": "cups", "meaning_up": "Romance, charm, imagination.", "meaning_rev": "Unrealistic, moody, jealous.", "desc": "A knight on a white horse holding a cup." },
  { "name": "Queen of Cups", "name_short": "cuqu", "value": "queen", "value_int": 13, "type": "cups", "meaning_up": "Compassion, calm, comfort.", "meaning_rev": "Martyrdom, insecurity, dependency.", "desc": "A queen seated on a throne by the sea." },
  { "name": "King of Cups", "name_short": "cuki", "value": "king", "value_int": 14, "type": "cups", "meaning_up": "Compassionate, calm, balance.", "meaning_rev": "Moodiness, emotional manipulation.", "desc": "A king seated on a throne floating on the sea." },
  // Swords
  { "name": "Ace of Swords", "name_short": "swac", "value": "ace", "value_int": 1, "type": "swords", "meaning_up": "Mental clarity, breakthrough, focus.", "meaning_rev": "Confusion, chaos, lack of clarity.", "desc": "A hand holding a sword upright, crowned with laurel." },
  { "name": "Two of Swords", "name_short": "sw02", "value": "2", "value_int": 2, "type": "swords", "meaning_up": "Indecision, choice, truce.", "meaning_rev": "Confusion, information overload.", "desc": "A blindfolded woman holding two swords." },
  { "name": "Three of Swords", "name_short": "sw03", "value": "3", "value_int": 3, "type": "swords", "meaning_up": "Heartbreak, sorrow, grief.", "meaning_rev": "Recovery, forgiveness, moving on.", "desc": "A heart pierced by three swords." },
  { "name": "Four of Swords", "name_short": "sw04", "value": "4", "value_int": 4, "type": "swords", "meaning_up": "Rest, meditation, contemplation.", "meaning_rev": "Restlessness, burnout, stagnation.", "desc": "A man resting in a tomb, with four swords on the wall." },
  { "name": "Five of Swords", "name_short": "sw05", "value": "5", "value_int": 5, "type": "swords", "meaning_up": "Conflict, tension, loss.", "meaning_rev": "Resentment, compromise, moving on.", "desc": "A man holding three swords, with two others walking away." },
  { "name": "Six of Swords", "name_short": "sw06", "value": "6", "value_int": 6, "type": "swords", "meaning_up": "Transition, moving on, departure.", "meaning_rev": "Emotional baggage, unresolved issues.", "desc": "A figure in a boat carrying swords across water." },
  { "name": "Seven of Swords", "name_short": "sw07", "value": "7", "value_int": 7, "type": "swords", "meaning_up": "Deception, strategy, stealth.", "meaning_rev": "Confession, conscience, regrets.", "desc": "A man stealing swords from a camp." },
  { "name": "Eight of Swords", "name_short": "sw08", "value": "8", "value_int": 8, "type": "swords", "meaning_up": "Imprisonment, powerlessness, self-victimization.", "meaning_rev": "Self-acceptance, freedom, releasing control.", "desc": "A blindfolded woman surrounded by eight swords." },
  { "name": "Nine of Swords", "name_short": "sw09", "value": "9", "value_int": 9, "type": "swords", "meaning_up": "Anxiety, hopelessness, nightmares.", "meaning_rev": "Hope, reach out, recovery.", "desc": "A person sitting up in bed, mourning over nine swords." },
  { "name": "Ten of Swords", "name_short": "sw10", "value": "10", "value_int": 10, "type": "swords", "meaning_up": "Betrayal, back-stabbing, rock bottom.", "meaning_rev": "Recovery, regeneration, new beginnings.", "desc": "A figure lying face down with ten swords in their back." },
  { "name": "Page of Swords", "name_short": "swpa", "value": "page", "value_int": 11, "type": "swords", "meaning_up": "New ideas, curiosity, mental energy.", "meaning_rev": "Hasty, all talk, cynical.", "desc": "A young person standing with a sword." },
  { "name": "Knight of Swords", "name_short": "swkn", "value": "knight", "value_int": 12, "type": "swords", "meaning_up": "Ambitious, action-oriented, driven.", "meaning_rev": "Restless, unfocused, impulsive.", "desc": "A knight charging on a horse." },
  { "name": "Queen of Swords", "name_short": "swqu", "value": "queen", "value_int": 13, "type": "swords", "meaning_up": "Independent, unbiased judgment, clear boundary.", "meaning_rev": "Cold-hearted, cruel, bitter.", "desc": "A queen seated on a throne decorated with butterflies." },
  { "name": "King of Swords", "name_short": "swki", "value": "king", "value_int": 14, "type": "swords", "meaning_up": "Mental clarity, intellectual power, truth.", "meaning_rev": "Quiet, manipulative, dictatorial.", "desc": "A king seated on a throne decorated with cherubs." },
  // Pentacles
  { "name": "Ace of Pentacles", "name_short": "peac", "value": "ace", "value_int": 1, "type": "pentacles", "meaning_up": "Opportunity, prosperity, new venture.", "meaning_rev": "Lost opportunity, lack of planning.", "desc": "A hand emerging from a cloud holding a pentacle over a garden." },
  { "name": "Two of Pentacles", "name_short": "pe02", "value": "2", "value_int": 2, "type": "pentacles", "meaning_up": "Balance, adaptability, prioritization.", "meaning_rev": "Disorganization, over-committed.", "desc": "A man juggling two pentacles." },
  { "name": "Three of Pentacles", "name_short": "pe03", "value": "3", "value_int": 3, "type": "pentacles", "meaning_up": "Teamwork, collaboration, skill.", "meaning_rev": "Lack of teamwork, solo work.", "desc": "Three figures working together in a cathedral." },
  { "name": "Four of Pentacles", "name_short": "pe04", "value": "4", "value_int": 4, "type": "pentacles", "meaning_up": "Security, conservation, frugality.", "meaning_rev": "Greed, possessiveness, blockage.", "desc": "A man holding onto four pentacles." },
  { "name": "Five of Pentacles", "name_short": "pe05", "value": "5", "value_int": 5, "type": "pentacles", "meaning_up": "Poverty, isolation, financial loss.", "meaning_rev": "Recovery, financial improvement.", "desc": "Two beggars in the snow outside a church window." },
  { "name": "Six of Pentacles", "name_short": "pe06", "value": "6", "value_int": 6, "type": "pentacles", "meaning_up": "Generosity, charity, giving/receiving.", "meaning_rev": "Debt, selfishness, one-sidedness.", "desc": "A man giving money to two beggars while holding scales." },
  { "name": "Seven of Pentacles", "name_short": "pe07", "value": "7", "value_int": 7, "type": "pentacles", "meaning_up": "Patience, investment, long-term view.", "meaning_rev": "Lack of reward, impatience.", "desc": "A man looking at his harvest of pentacles." },
  { "name": "Eight of Pentacles", "meaning_up": "Apprenticeship, mastery, skill.", "meaning_rev": "Perfectionism, misdirected activity, uninspired.", "name_short": "pe08", "value": "8", "value_int": 8, "type": "pentacles", "desc": "A craftsman carving pentacles." },
  { "name": "Nine of Pentacles", "name_short": "pe09", "value": "9", "value_int": 9, "type": "pentacles", "meaning_up": "Independence, luxury, self-sufficiency.", "meaning_rev": "Over-investment in work, lack of enjoyment.", "desc": "A woman in a lush garden with a bird on her hand." },
  { "name": "Ten of Pentacles", "name_short": "pe10", "value": "10", "value_int": 10, "type": "pentacles", "meaning_up": "Legacy, inheritance, wealth.", "meaning_rev": "Financial failure, family dispute.", "desc": "An elderly man seated with family and dogs." },
  { "name": "Page of Pentacles", "name_short": "pepa", "value": "page", "value_int": 11, "type": "pentacles", "meaning_up": "Manifestation, financial opportunity, skill.", "meaning_rev": "Lack of progress, procrastination.", "desc": "A young person looking at a pentacle." },
  { "name": "Knight of Pentacles", "name_short": "pekn", "value": "knight", "value_int": 12, "type": "pentacles", "meaning_up": "Practical, reliable, hard-working.", "meaning_rev": "Boring, static, lazy.", "desc": "A knight on a horse holding a pentacle." },
  { "name": "Queen of Pentacles", "name_short": "pequ", "value": "queen", "value_int": 13, "type": "pentacles", "meaning_up": "Nurturing, practical, providing.", "meaning_rev": "Self-centered, ungrounded, smothering.", "desc": "A queen seated in a garden with a rabbit." },
  { "name": "King of Pentacles", "name_short": "peki", "value": "king", "value_int": 14, "type": "pentacles", "meaning_up": "Abundance, discipline, prosperity.", "meaning_rev": "Greedy, indulgent, obsessed with wealth.", "desc": "A king seated on a throne decorated with bulls' heads." }
];
